// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abfjkezjadjoecaoepuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiZmprZXpqYWRqb2VjYW9lcHV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NzIzMjYsImV4cCI6MjA2NzM0ODMyNn0.mqXkuOSJsX0zKUkPNPI3Cfbn0wnemdd76Tj4D7yjRPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});